### ISSUE TITLE
hide and seek 

### ISSUE THREAD

**Issue by techmoves** [gergitokusse/Portfolio-setup-and-mobile-first#14]
well done on your project  you did very well✔️🎆🎉🎉🎉🎉🎉🎉👍

![RollSpinGIF](https://user-images.githubusercontent.com/110924992/233313821-5d308c34-958a-4e8f-b043-06e7bebea55a.gif)

how ever I notice on your JavaScript file there is the syntax error on line 338
![image](https://user-images.githubusercontent.com/110924992/233312871-784682dd-62a9-4885-9105-5ce93890a80f.png)

syntax error fixed
![image](https://user-images.githubusercontent.com/110924992/233315313-44568784-887d-4e9f-a598-86104b192639.png)

**Comment by gergitokusse** [comment]
# 🙏🙏🙏🙏🙏🙏🙏🙏
